stages:
    data_ingestion:
        cmd: python src/mlops_project/pipeline/stage_01_data_ingestion.py
        deps:
            - src/mlops_project/pipeline/stage_01_data_ingestion.py
            - src/mlops_project/components/data_ingestion.py
            - config/config.yaml
        outs:
            - artifacts/data_ingestion/Churn_Modelling.csv
            - artifacts/data_ingestion/data.zip
    
    data_validation:
        cmd: python src/mlops_project/pipeline/stage_02_data_validation.py
        deps:
            - src/mlops_project/pipeline/stage_02_data_validation.py
            - src/mlops_project/components/data_validation.py
            - artifacts/data_ingestion/Churn_Modelling.csv
            - config/config.yaml
            - schema.yaml
        outs:
            - artifacts/data_validation/status.txt

    data_transformation:
        cmd: python src/mlops_project/pipeline/stage_03_data_transformation.py
        deps:
            - src/mlops_project/pipeline/stage_03_data_transformation.py
            - src/mlops_project/components/data_transformation.py
            - artifacts/data_validation/status.txt
            - config/config.yaml
        outs:
            - artifacts/data_transformation/preprocessor.joblib
            - artifacts/data_transformation/train.csv
            - artifacts/data_transformation/test.csv

    model_training:
        cmd: python src/mlops_project/pipeline/stage_04_model_trainer.py
        deps:
            - src/mlops_project/pipeline/stage_04_model_trainer.py
            - src/mlops_project/components/model_trainer.py
            - artifacts/data_transformation/preprocessor.joblib
            - artifacts/data_transformation/train.csv
            - config/config.yaml
            - params.yaml
        params:
            - params.yaml
        outs:
            - artifacts/model_trainer/model.joblib
    
    model_evaluation:
        cmd: python src/mlops_project/pipeline/stage_05_model_evaluation.py
        deps:
            - src/mlops_project/pipeline/stage_05_model_evaluation.py
            - src/mlops_project/components/model_evaluation.py
            - artifacts/model_trainer/model.joblib
            - artifacts/data_transformation/test.csv
            - config/config.yaml
        metrics:
            - artifacts/model_evaluation/metrics.json
    
