name: Deploy CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE: customer-churn-prediction
  DOCKER_REGISTRY: ghcr.io
  IMAGE_TAG: ${{ github.sha }}
  CONTAINER_NAME: customer-churn-prediction-container
  LOG_FILE: deploy.log
  PREVIOUS_IMAGE_TAG: ${{ github.sha }}-previous

jobs:
  data_ingestion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download data
        env:
          DATA_URL: ${{ secrets.DATA_URL }}
        run: |
          echo "Downloading data from ${DATA_URL}..." >> $LOG_FILE
          wget -O ${GITHUB_WORKSPACE}/artifacts/data_ingestion/data.zip $DATA_URL
          unzip ${GITHUB_WORKSPACE}/artifacts/data_ingestion/data.zip -d ${GITHUB_WORKSPACE}/artifacts/data_ingestion/
        continue-on-error: true
        env:
          LOG_FILE: ${{ env.LOG_FILE }}

  data_validation:
    runs-on: ubuntu-latest
    needs: data_ingestion
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate data
        run: |
          echo "Validating data..." >> $LOG_FILE
          python validate_data.py
        continue-on-error: true
        env:
          LOG_FILE: ${{ env.LOG_FILE }}

  data_transformation:
    runs-on: ubuntu-latest
    needs: data_validation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Transform data
        run: |
          echo "Transforming data..." >> $LOG_FILE
          python transform_data.py
        continue-on-error: true
        env:
          LOG_FILE: ${{ env.LOG_FILE }}

  model_training:
    runs-on: ubuntu-latest
    needs: data_transformation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate test data for evaluation
        run: |
          echo "Generating test data..." >> $LOG_FILE
          python generate_test_data.py
        env:
          LOG_FILE: ${{ env.LOG_FILE }}

      - name: Train model with dummy data
        run: |
          echo "Training model with dummy data..." >> $LOG_FILE
          python src/mlops_project/train_model.py --use_dummy
        env:
          LOG_FILE: ${{ env.LOG_FILE }}

      - name: Verify model file
        run: |
          echo "Verifying model file..." >> $LOG_FILE
          ls -l models/model.pkl || echo "Model file not found" >> $LOG_FILE
          file models/model.pkl || echo "Cannot get file type" >> $LOG_FILE
          echo "Model file size: $(stat -f %z models/model.pkl 2>> $LOG_FILE || echo '0') bytes" >> $LOG_FILE

      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: model
          path: models/model.pkl

      - name: Upload test data artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-data
          path: |
            data/test_data.csv
            data/test_labels.csv

  model_evaluation:
    runs-on: ubuntu-latest
    needs: model_training
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download model artifact
        uses: actions/download-artifact@v3
        with:
          name: model
          path: models/

      - name: Download test data artifacts
        uses: actions/download-artifact@v3
        with:
          name: test-data
          path: data/

      - name: Verify downloaded files
        run: |
          echo "Verifying downloaded files..." >> $LOG_FILE
          ls -l models/model.pkl || echo "Model file not found" >> $LOG_FILE
          file models/model.pkl || echo "Cannot get file type" >> $LOG_FILE
          echo "Model file size: $(stat -f %z models/model.pkl 2>> $LOG_FILE || echo '0') bytes" >> $LOG_FILE
          ls -l data/test_data.csv data/test_labels.csv || echo "Test data files not found" >> $LOG_FILE

      - name: Evaluate model
        run: |
          echo "Evaluating model..." >> $LOG_FILE
          python scripts/evaluate_model.py
        env:
          LOG_FILE: ${{ env.LOG_FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: model_evaluation
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download model artifact
        uses: actions/download-artifact@v3
        with:
          name: model
          path: models/

      - name: Build Docker image
        run: |
          echo "Building Docker image..." >> $LOG_FILE
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }} . 2>> $LOG_FILE || echo "Error building Docker image!" >> $LOG_FILE

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: |
          echo "Pushing Docker image to registry..." >> $LOG_FILE
          docker push ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }} 2>> $LOG_FILE || echo "Error pushing Docker image!" >> $LOG_FILE

      - name: Record current deployment
        if: success()
        run: |
          echo ${{ env.IMAGE_TAG }} > current_deployment.txt
          cat current_deployment.txt >> $LOG_FILE

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            echo "Logging deployment process..." > /tmp/${{ env.LOG_FILE }}
            echo "Stopping old container..." >> /tmp/${{ env.LOG_FILE }}
            docker stop ${{ env.CONTAINER_NAME }} || true
            echo "Removing old container..." >> /tmp/${{ env.LOG_FILE }}
            docker rm ${{ env.CONTAINER_NAME }} || true
            echo "Pulling new image..." >> /tmp/${{ env.LOG_FILE }}
            docker pull ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}
            
            echo "Running health check on new image..." >> /tmp/${{ env.LOG_FILE }}
            if docker run --rm ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }} python -c "import sys; sys.exit(0 if 'Healthy' in open('/app/health.txt').read() else 1)"; then
              echo "Health check passed. Starting new container..." >> /tmp/${{ env.LOG_FILE }}
              docker run -d --name ${{ env.CONTAINER_NAME }} -p 80:80 ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}
              echo "Deployment successful." >> /tmp/${{ env.LOG_FILE }}
            else
              echo "Health check failed. Initiating rollback..." >> /tmp/${{ env.LOG_FILE }}
              if [ -f current_deployment.txt ]; then
                PREVIOUS_IMAGE_TAG=$(cat current_deployment.txt)
                echo "Rolling back to $PREVIOUS_IMAGE_TAG" >> /tmp/${{ env.LOG_FILE }}
                docker pull ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE }}:$PREVIOUS_IMAGE_TAG
                docker run -d --name ${{ env.CONTAINER_NAME }} -p 80:80 ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE }}:$PREVIOUS_IMAGE_TAG
                echo "Rollback successful." >> /tmp/${{ env.LOG_FILE }}
              else
                echo "No previous deployment found. Manual intervention required." >> /tmp/${{ env.LOG_FILE }}
                exit 1
              fi
            fi

      - name: Upload deployment log
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: deployment-log
          path: ${{ env.LOG_FILE }}

      - name: Notify Slack on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          status: ${{ job.status }}
          color: danger
          message: Deployment failed for ${{ github.repository }} on ${{ github.ref }} at ${{ github.sha }}. A rollback was attempted. Check logs for details.

      - name: Notify Slack on success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          status: ${{ job.status }}
          color: good
          message: Deployment successful for ${{ github.repository }} on ${{ github.ref }} at ${{ github.sha }}. Check logs for details.
